<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="../src/box.css">
    <script src="https://cdn.tailwindcss.com"></script>
    <title>Error</title>
</head>
<body>
    <div class="font-sans w-full bg-black relative overflow-hidden w-screen h-screen flex items-center justify-center text-white">
        <div class="absolute z-10 text-center drop-shadow-lg">
            <h1 class="text-9xl text-red-600 font-semibold err">404</h1>
            <h2 class="text-4xl text-red-700 font-semibold err">ERROR! PAGE NOT FOUND</h2>
        </div>

        <!-- BG -->
        <div class="absolute w-[500%] rotate-[-45deg]">
            <div class="pb-5 text-xl item">ERROR ERROR ERROR ERROR
            ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR
            ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR
            ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR
            ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR
            ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR
            ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR
            </div>

            <div class="pb-5 text-xl item">ERROR ERROR ERROR ERROR
            ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR
            ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR
            ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR
            ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR
            ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR
            ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR
           
            </div>

            <div class="pb-5 text-xl item">ERROR ERROR ERROR ERROR
            ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR
            ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR
            ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR
            ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR
            ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR
            ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR
            </div>

            <div class="pb-5 text-xl item">ERROR ERROR ERROR ERROR
            ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR
            ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR
            ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR
            ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR
            ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR
            ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR
            </div>

            <div class="pb-5 text-xl item">ERROR ERROR ERROR ERROR
            ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR
            ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR
            ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR
            ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR
            ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR
            ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR
            </div>

            <div class="pb-5 text-xl item">ERROR ERROR ERROR ERROR
            ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR
            ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR
            ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR
            ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR
            ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR
            ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR
            </div>

            <div class="pb-5 text-xl item">ERROR ERROR ERROR ERROR
            ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR
            ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR
            ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR
            ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR
            ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR
            ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR
            </div>
            
            <div class="pb-5 text-xl item">ERROR ERROR ERROR ERROR
            ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR
            ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR
            ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR
            ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR
            ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR
            ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR
            </div>

            <div class="pb-5 text-xl item">ERROR ERROR ERROR ERROR
            ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR
            ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR
            ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR
            ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR
            ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR
            ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR
            </div>

            <div class="pb-5 text-xl item">ERROR ERROR ERROR ERROR
            ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR
            ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR
            ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR
            ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR
            ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR
            ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR
            </div>

            <div class="pb-5 text-xl item">ERROR ERROR ERROR ERROR
            ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR
            ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR
            ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR
            ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR
            ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR
            ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR
            </div>

            <div class="pb-5 text-xl item">ERROR ERROR ERROR ERROR
            ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR
            ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR
            ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR
            ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR
            ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR
            ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR
            </div>

            <div class="pb-5 text-xl item">ERROR ERROR ERROR ERROR
            ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR
            ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR
            ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR
            ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR
            ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR
            ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR
            </div>

            <div class="pb-5 text-xl item">ERROR ERROR ERROR ERROR
            ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR
            ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR
            ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR
            ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR
            ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR
            ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR
            </div>

            <div class="pb-5 text-xl item">ERROR ERROR ERROR ERROR
            ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR
            ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR
            ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR
            ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR
            ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR
            ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR
            </div>

            <div class="pb-5 text-xl item">ERROR ERROR ERROR ERROR
            ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR
            ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR
            ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR
            ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR
            ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR
            ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR
            </div>

            <div class="pb-5 text-xl item">ERROR ERROR ERROR ERROR
            ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR
            ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR
            ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR
            ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR
            ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR
            ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR
            </div>

            <div class="pb-5 text-xl item">ERROR ERROR ERROR ERROR
            ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR
            ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR
            ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR
            ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR
            ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR
            ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR
            </div>

            <div class="pb-5 text-xl item">ERROR ERROR ERROR ERROR
            ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR
            ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR
            ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR
            ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR
            ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR
            ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR
            </div>

            <div class="pb-5 text-xl item">ERROR ERROR ERROR ERROR
            ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR
            ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR
            ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR
            ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR
            ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR
            ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR
            </div>

            <div class="pb-5 text-xl item">ERROR ERROR ERROR ERROR
            ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR
            ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR
            ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR
            ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR
            ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR
            ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR
            </div>

            <div class="pb-5 text-xl item">ERROR ERROR ERROR ERROR
            ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR
            ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR
            ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR
            ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR
            ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR
            ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR
            </div>

            <div class="pb-5 text-xl item">ERROR ERROR ERROR ERROR
            ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR
            ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR
            ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR
            ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR
            ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR
            ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR
            </div>

            <div class="pb-5 text-xl item">ERROR ERROR ERROR ERROR
            ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR
            ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR
            ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR
            ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR
            ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR
            ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR
            </div>

            <div class="pb-5 text-xl item">ERROR ERROR ERROR ERROR
            ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR
            ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR
            ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR
            ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR
            ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR
            ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR
            </div>

            <div class="pb-5 text-xl item">ERROR ERROR ERROR ERROR
            ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR
            ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR
            ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR
            ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR
            ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR
            ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR
            </div>
        </div>    
    </div>

    <style>
        .item{
            animation: moving 6s linear infinite;
        }

        .item:nth-child(even){
            color:red;
            text-shadow: 0 0 1px #fff;
            animation: moving 6s linear infinite reverse;
        }

        @keyframes moving {
            100%{
                transform: translate(800px);
            }
        }

        .err {
        animation:err-animation 1.5s infinite;
    }
    @keyframes err-animation {
        0% {
            opacity: 1;
        }
        50% {
            opacity: 0;
        }
        100% {
            opacity: 1;
        }
    }

       
    </style>
</body>
</html>